'use strict'

var ZC_NUM_JS_INPUTS = 2
var ZC_NUM_JS_OUTPUTS = 2

var ZC_NOTEPLAINTEXT_LEADING = 1
var ZC_V_SIZE = 8
var ZC_RHO_SIZE = 32
var ZC_R_SIZE = 32
var ZC_MEMO_SIZE = 512

var ZC_NOTEPLAINTEXT_SIZE = (
  ZC_NOTEPLAINTEXT_LEADING +
  ZC_V_SIZE +
  ZC_RHO_SIZE +
  ZC_R_SIZE +
  ZC_MEMO_SIZE
)

var NOTEENCRYPTION_AUTH_BYTES = 16

var ZC_NOTECIPHERTEXT_SIZE = (
  ZC_NOTEPLAINTEXT_SIZE +
  NOTEENCRYPTION_AUTH_BYTES
)

module.exports = {
  ZC_MEMO_SIZE: ZC_MEMO_SIZE,
  ZC_NOTECIPHERTEXT_SIZE: ZC_NOTECIPHERTEXT_SIZE,
  ZC_NUM_JS_INPUTS: ZC_NUM_JS_INPUTS,
  ZC_NUM_JS_OUTPUTS: ZC_NUM_JS_OUTPUTS
}
